using System.Collections;
using System.Collections.Generic;
using UnityEngine;


public class MusicManager : MonoBehaviour
{
    private static MusicManager instance;

    void Awake()
    {
        if (instance != null && instance != this)
        {
            Destroy(gameObject); // nếu đã có 1 bản đang chạy, xóa bản mới
        }
        else
        {
            instance = this;
            DontDestroyOnLoad(gameObject); // giữ lại khi chuyển cảnh
        }
    }
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
